"""Export the shared knowledge base (GMs, repertoires, curricula, advice texts)
from the Python package to web/data.js so the web app uses the same content.

    python scripts/build_web_data.py
"""
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from chess_trainer import knowledge as k  # noqa: E402
from chess_trainer.analyze import TAGS  # noqa: E402
from chess_trainer.plan import PHASES, WEEKDAYS  # noqa: E402
from chess_trainer.report import ADVICE  # noqa: E402

data = {
    "DIMS": list(k.DIMS), "DIM_LABEL": k.DIM_LABEL, "GRANDMASTERS": k.GRANDMASTERS,
    "ARCHETYPES": k.ARCHETYPES, "REPERTOIRE": k.REPERTOIRE, "TACTIC_THEMES": k.TACTIC_THEMES,
    "ENDGAME_CURRICULUM": k.ENDGAME_CURRICULUM, "STRATEGY_THEMES": k.STRATEGY_THEMES,
    "TAGS": TAGS, "PHASES": PHASES, "WEEKDAYS": WEEKDAYS, "ADVICE": ADVICE,
}
out = Path(__file__).resolve().parent.parent / "web" / "data.js"
body = "".join(f"export const {name} = {json.dumps(val, ensure_ascii=False, indent=1)};\n" for name, val in data.items())
out.write_text("// Generated by scripts/build_web_data.py from chess_trainer/ – do not edit by hand.\n" + body,
               encoding="utf-8")
print(f"wrote {out}")
